# https://github.com/berberman/nvfetcher?tab=readme-ov-file#keyfile
[hyprland-workspaces]
src.github = "FieldofClay/hyprland-workspaces"
fetch.github = "FieldofClay/hyprland-workspaces"

[joker]
src.github_tag = "candid82/joker"
fetch.github = "candid82/joker"

[kamp]
src.github_tag = "kyleisah/Klipper-Adaptive-Meshing-Purging"
fetch.github = "kyleisah/Klipper-Adaptive-Meshing-Purging"

[kibana]
src.container = "library/kibana"
src.include_regex = "7\\..*"
fetch.docker = "library/kibana"

[linux-rockchip]
src.git = "https://github.com/armbian/linux-rockchip.git"
src.branch = "rk-5.10-rkr6"
fetch.github = "armbian/linux-rockchip"

[pin-github-action]
src.github_tag = "mheap/pin-github-action"
fetch.github = "mheap/pin-github-action"

[sf-mono-nerd-font]
src.github = "epk/SF-Mono-Nerd-Font"
fetch.github = "epk/SF-Mono-Nerd-Font"

[tfautomv]
src.github_tag = "busser/tfautomv"
fetch.github = "busser/tfautomv"
