# https://github.com/berberman/nvfetcher?tab=readme-ov-file#keyfile
[antifennel]
src.git = "https://git.sr.ht/~technomancy/antifennel"
fetch.git = "https://git.sr.ht/~technomancy/antifennel"

[flake-registry]
src.git = "https://github.com/nixos/flake-registry"
fetch.github = "nixos/flake-registry"

[hyprland-workspaces]
src.github = "FieldofClay/hyprland-workspaces"
fetch.github = "FieldofClay/hyprland-workspaces"

[harper-ls]
src.github = "elijah-potter/harper"
fetch.github = "elijah-potter/harper"

[joker]
src.github_tag = "candid82/joker"
fetch.github = "candid82/joker"

[kamp]
src.github_tag = "kyleisah/Klipper-Adaptive-Meshing-Purging"
fetch.github = "kyleisah/Klipper-Adaptive-Meshing-Purging"

[linux-rockchip]
src.git = "https://github.com/armbian/linux-rockchip.git"
src.branch = "rk-5.10-rkr6"
fetch.github = "armbian/linux-rockchip"

[mealie]
src.container = "hkotel/mealie"
src.include_regex = "latest"
fetch.docker = "hkotel/mealie"

[sf-mono-nerd-font]
src.github = "epk/SF-Mono-Nerd-Font"
fetch.github = "epk/SF-Mono-Nerd-Font"
